### PR TITLE
feat: support validating list of oci artifacts

### PR DESCRIPTION
**Pull request by ahmad-ibra**
This PR simply adds support for validating a list of artifacts that exist within a defined registry

### CODE REVIEW

**Review by TylerGillson — CHANGES_REQUESTED** [review]
These changes all look good, but what about validating a specific tag or digest? We need to be able to do that.

**Comment by ahmad-ibra** [comment]
Updated so that you can validate a particular artifact by tag or by digest. For instance:
```
      repositoryPaths:
        - "spectro-images/gcr.io/spectro-images-fips/mongo/mongo-sidecar"
        - "spectro-images/gcr.io/spectro-images-fips/kube-apiserver@v1.26.5"
        - "spectro-images/gcr.io/spectro-images-fips/kube-scheduler@sha256:65ae8fd8713ede1977d26991821ba7eb3beb48ec575b31947568f30dbdd36862"
```

**Review by TylerGillson — CHANGES_REQUESTED** [review]
Looks good, but you're not populating `vr.Failures` in the event of an error.

**Review by TylerGillson — APPROVED** [review]
lgtm

**Pull request merged**
